Controllers/TPurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionInventoryDAL.Entity;
using AuctionInventoryDAL.Repositories;
using AuctionInventory.Services;
using AuctionInventory.Models;
using AuctionInventory.Helpers;
using OfficeOpenXml;
using AuctionInventory.MyRoleProvider;
using System.Security.Cryptography;
using System.IO;
using System.Text;

namespace AuctionInventory.Controllers
{
    [Permissions(Permissions.View)]
    public class TPurchaseController : Controller
    {
        private AuctionInventoryEntities auctionContext = new AuctionInventoryEntities();


        // GET: TPurchase
        public ActionResult Index()
        {
            ViewBag.PageName = "Create Purchase";
            return View();
        }


        public ActionResult PurchaseReport()
        {
            return View();
        }


        [HttpPost]
        public ActionResult GenerateCustomPDF()
        {
            dynamic vehicle = 0;
            try
            {
                if (ModelState.IsValid)
                {

                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    vehicle = purchaseServiceClient.GenerateCustomPDF();
                    //return Json(vehicle, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                vehicle = null;
                throw e;
            }

            return Json(vehicle, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GenerateInvoicePDF()
        {
            dynamic vehicle = 0;
            try
            {
                if (ModelState.IsValid)
                {

                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    vehicle = purchaseServiceClient.GenerateInvoicePDF();
                    //return Json(vehicle, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                vehicle = null;
                throw e;
            }
            return Json(vehicle, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetData(int id)
        {
            dynamic listVehicle = 0;

            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    listVehicle = purchaseServiceClient.GetDataVehiclelist(id);

                    //return Json(new { vehicle }, JsonRequestBehavior.AllowGet);
                }
            }
            // Please through Exeption Everywhere
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Wrong");
                listVehicle = null;
                throw e;
            }
            return Json(listVehicle, JsonRequestBehavior.AllowGet);
            //return vehicle;
        }



        [HttpPost]
        public ActionResult DeleteVehicle(int iVehicleID)
        {

            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    status = purchaseServiceClient.DeleteVehicle(iVehicleID);
                    //return RedirectToAction("GetPurchaseList", "TPurchase");
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong!");
                status = false;
                throw e;
            }

            return new JsonResult { Data = new { status = status } };

        }

        [HttpPost]
        public JsonResult GetSupplierAddress(int id)
        {
            dynamic listVehicle = 0;

            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    listVehicle = purchaseServiceClient.GetSupplierAddress(id);

                    //return Json(new { vehicle }, JsonRequestBehavior.AllowGet);
                }
            }
            // Please through Exeption Everywhere
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Wrong");
                listVehicle = null;
                throw e;
            }
            return Json(listVehicle, JsonRequestBehavior.AllowGet);
            //return vehicle;
        }

        [HttpGet]
        public ActionResult UpdateIndex(String ID)
        {
            int id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));
            Purchase purchase = new Purchase();
            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    purchase = purchaseServiceClient.GetPurchase(id);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                purchase = null;
                throw e;
            }
            return View(purchase);
        }


        //[HttpPost]
        //public ActionResult UpdateIndex(Purchase purchase, List<Vehicles> griddata)
        //{
        //    bool status = false;
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
        //            status = purchaseServiceClient.SaveData(purchase, griddata);
        //            return RedirectToAction("GetPurchaseList", "TPurchase");
        //        }
        //    }
        //    catch (Exception e)
        //    {
        //        ModelState.AddModelError("error", "Something Went Wrong");
        //        status = false;
        //        throw e;
        //    }

        //    return Json(new { status = true }, JsonRequestBehavior.AllowGet);
        //    //return new JsonResult { Data = new { status = status ,purID=purchase.PurchaseID} };

        //}

        public ActionResult Upload()
        {
            return View();
        }


        #region Lots
        public ActionResult PurchaseLotList()
        {
            ViewBag.PageName = "Purchase Lot List";
            return View();
        }


        public ActionResult GetAllLots()
        {
            dynamic lots = 0;

            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    lots = purchaseServiceClient.GetAllLots();

                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Wrong");
                lots = null;
                throw e;

            }
            return Json(lots, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult SavePurchaseLot(string ID)
        {
            int id = 0;
            if (ID != "0")
            {
                id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));
            }
            Lots lot = new Lots();
            lot.iLotID = id;

            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    lot = purchaseServiceClient.GetLots(id);
                    ViewBag.PageName = " Create Purchase Lot";
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                lot = null;
                throw e;
            }
            return View(lot);
        }

        [HttpPost]
        public ActionResult SavePurchaseLot(Lots lot)
        {

            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();

                    status = purchaseServiceClient.SavePurchaseLot(lot);
                    //return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong");
                status = false;
                throw e;

            }
            return View("PurchaseLotList", lot);
            //   return new JsonResult { Data = new { status = status } };
        }


        [HttpGet]
        public ActionResult DeletePurchaseLot(string ID)
        {
            int id = 0;
            if (ID != "0")
            {
                id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));
            }
            Lots lot = new Lots();
            lot.iLotID = id;

            try
            {
                if (ModelState.IsValid)
                {
                    PurchaseServiceClient purchaseServiceClient = new PurchaseServiceClient();
                    lot = purchaseServiceClient.GetLots(id);

                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                lot = null;
                throw e;
            }
            return View("DeletePurchaseLot", lot);
        }

        [HttpPost]
        [ActionName("DeletePurchaseLot")]

Views/TPurchase/DeletePurchaseLot.cshtml
@model AuctionInventory.Models.Lots
@{
    ViewBag.Title = "DeletePurchaseLot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("DeleteExpenseLot", "MExpenses", FormMethod.Post, new { id = "popupForm" }))
{

    if (Model != null && Model.iLotID > 0)
    {
        @Html.HiddenFor(a => a.iLotID)

    }

    <div class="row">

        <div class="col-md-4">
            <div class="form-group">
                @Html.TextBoxFor(a => a.chLotType, new { @type = "hidden", @id = "hdnLotType" })
                <label>Lot Name:</label>
                @Html.TextBoxFor(a => a.strLotName, new { @class = "form-control", @id = "txtLotName" })
                @Html.ValidationMessageFor(a => a.strLotName)
            </div>
        </div>
        <div class="col-md-4">

            <div class="form-group">
                <label>From Date:</label>
                @Html.TextBoxFor(a => a.dtFromDate, new { @type = "hidden", @id = "dtFromDate" })

                @Html.TextBoxFor(a => a.strFromDate, new { @class = "form-control datepicker", @name = "DateTextBox", @id = "txtFromDate", @placeholder = "Enter Drop-off date here..." })
                @Html.ValidationMessageFor(a => a.strFromDate)
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label>To Date:</label>

                @Html.TextBoxFor(a => a.dtToDate, new { @type = "hidden", @id = "dtToDate" })

                @Html.TextBoxFor(a => a.strToDate, new { @class = "form-control datepicker", @name = "DateTextBox", @id = "txtToDate", @placeholder = "Enter Drop-off date here..." })
                @Html.ValidationMessageFor(a => a.strToDate)
            </div>

        </div>

        <input type="submit" name='dailogBox' style="margin-left: 400px;" id="btnDelete" class="btn btn-danger col-md-1" value="Delete">
    </div>

}
<br />


<script type="text/javascript">
    $(function () { // will trigger when the document is ready


        debugger
        $('.datepicker').datepicker({ dateFormat: 'mm/dd/yy' }); //Initialise any date pickers
       

        $('.datepicker').datepicker({ dateFormat: 'mm/dd/yy' }); //Initialise any date pickers
      

        $("#dtFromDate").val($("#txtFromDate").val());
        $("#dtToDate").val($("#txtToDate").val());
        $("#hdnLotType").val('S');

        if (Model.iLotID == 0) {

            $("#txtFromDate").val("");
            $("#txtToDate").val("");
            $("#hdnLotType").val("");
            $("#dtFromDate").val("");
            $("#dtToDate").val("");
            $("#txtLotName").val("");

        }

    });





</script>

Views/TPurchase/GetGriddata.cshtml
@*@model AuctionInventory.Models.Vehicles*@
@model IEnumerable<AuctionInventory.Models.Vehicles>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    span.field-validation-error {
        color: red;
    }
    /*we have overrides the css to change border color of menus*/
    .navbar-inverse {
        background-color: #337ab7;
        border-color: #333;
    }

    #divDetails #divParsedExcel {
        margin-right: 5%;
        margin-left: 5%;
    }
</style>

<div class="box-body">
    <table id="myDatatable">
       
        <thead>
            <tr>
                <th>Purchase ID</th>
                <th>InvoiceNo</th>
                <th>InvoiceDate</th>
                <th>SupplierName</th>
                <th>MasterDecNo</th>
                <th>BLNo</th>
                <th>ArrivalDate</th>
                <th>ConversionRate</th>
                <th>AED</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
    </table>
</div>
<script>
    $(document).ready(function () {
        $('#myDatatable').DataTable({
            "scrollY": 400,
            "scrollX": true,
            "ajax": {
                "url": '/TPurchase/GetAllPurchase',
                "type": "get",
                "datatype": "json"
            },
            "columns": [
                { "data": "PurchaseID", "autoWidth": true },
                { "data": "iPurchaseInvoiceNo", "autoWidth": true },
                { "data": "strPurchaseInvoiceDate", "autoWidth": true },
                { "data": "strSupplierName", "autoWidth": true },
                { "data": "strMasterDecNo", "autoWidth": true },
                { "data": "strBLNo", "autoWidth": true },
                { "data": "strArrivalDate", "autoWidth": true },
                //{ "data": "strInvoiceValue", "autoWidth": true },
                { "data": "dmlConversionRate", "autoWidth": true },
                { "data": "iAED", "autoWidth": true },

                {
                    "data": "PurchaseID", "width": "50px", "render": function (data) {
                        return '<a  href="/TPurchase/UpdateIndex/' + data + '">Edit</a>';
                    }
                },
                {
                    "data": "PurchaseID", "width": "50px", "render": function (data) {
                        return '<a  href="/TPurchase/delete/' + data + '">Delete</a>';
                    }
                }
            ]
        })
    });
</script>


    @*<div class="box-body">
        <div class="row">
            <table id="dataGrid" class="table table-bordered table-striped"></table>
            <div id="pagingGrid"></div>
        </div>
    </div>

    <script>
        var end;
        $(document).ready(function () {

            $('#dataGrid').jqGrid({

                url: '/TPurchase/GetAllPurchase/',
                datatype: "json",
                contentType: "application/json; charset-utf-8",
                mtype: 'GET',
                colNames: ['Purchase ID', 'InvoiceNo', 'InvoiceDate', 'SupplierName', 'MasterDecNo', 'BLNo', 'ArrivalDate', 'ConversionRate', 'AED', 'Action'],
                colModel: [
                     { name: 'PurchaseID', index: 'PurchaseID', editable: true },
                    { name: 'iPurchaseInvoiceNo', index: 'iPurchaseInvoiceNo', editable: true },
                    { name: 'strPurchaseInvoiceDate', index: 'strPurchaseInvoiceDate', editable: true },
                    { name: 'strSupplierName', index: 'strSupplierName', editable: true },
                    { name: 'strMasterDecNo', index: 'strMasterDecNo', editable: true },
                    { name: 'strBLNo', index: 'strBLNo', editable: true },
                    { name: 'strArrivalDate', index: 'strArrivalDate', editable: true },
                    { name: 'dmlConversionRate', index: 'dmlConversionRate', editable: true },
                     { name: 'iAED', index: 'iAED', editable: true },
                    //{ name: 'act', index: 'act', width: 350 }

                    {
                        name: 'Action', index: 'Action', align: 'center', width: 200, search: false, title: false,
                        formatter: function (cellvalue, options, rowObject) {
                            return '<a class=" btn btn-info" href="/MVehicle/Save/' + options.rowId + '">' + "Edit" + '</a>' + "     " + '<a class="btn btn-info" href="/MVehicle/Delete/' + options.rowId + '">' + "Delete" + '</a>';

                        }
                    },

                ],
                width: 1050,
                height: 250,
                rowNum: 10,
                loadonce: true,
                rowList: [10, 20, 30],
                pager: 'pagingGrid',
                caption: 'Select Invoice to edit',
                //cellEdit: true,
                //cellsubmit: 'clientArray',
                //gridComplete: function () {

                //    var ids = jQuery("#dataGrid").jqGrid('getDataIDs');

                //    for (var i = 0; i < ids.length; i++) {
                //        var cl = ids[i];
                //        be = "<input class='popup btn btn-info' style='margin-right: 5%; margin-left: 8%;' type='button' value='Edit' onclick=\"jQuery('#dataGrid').editRow('" + cl + "');\"  />";
                //        se = "<input class='popup btn btn-info' style='margin-right: 5%; ' type='button' value='Save' onclick=\"jQuery('#dataGrid').saveRow('" + cl + "');\"  />";
                //        ce = "<input class='popup btn btn-info' style='margin-right: 5%; ' type='button' value='Cancel' onclick=\"jQuery('#dataGrid').restoreRow('" + cl + "');\" />";
                //        jQuery("#dataGrid").jqGrid('setRowData', ids[i], { act: be + se + ce });
                //    }
                //},
            });
            jQuery("#dataGrid").jqGrid('filterToolbar', { stringResult: true, searchOnEnter: false, defaultSearch: "cn" });
            jQuery("#dataGrid").jqGrid('navGrid', '#pagingGrid', { edit: false, add: false, del: false, search: false });

        });
    </script>*@

<!-- JqGrid Scripts -->
@*<link href="~/scripts/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
<link href="~/scripts/ui.jqgrid.css" rel="stylesheet" />
<script src="~/scripts/jQuery-migrate-1.2.1.js"></script>
<script src="~/scripts/grid.locale-en.js"></script>
<script src="~/scripts/jquery.jqgrid.min.js"></script>*@

Views/TPurchase/Save.cshtml
@model AuctionInventory.Models.Purchase
@{
    ViewBag.Title = "Save";
    Layout = null;
}

<style>
    #divDetails {
        margin-right: 5%;
        margin-left: 5%;
    }
</style>

@*@using (Html.BeginForm("save", "TPurchase", FormMethod.Post, new { id = "popupForm" }))*@
@*@using (Html.BeginForm("Upload", "TPurchase", FormMethod.Post, new { enctype = "multipart/form-data" })) *@

@*@using (Ajax.BeginForm("Upload", "TPurchase", null, new AjaxOptions() { OnSuccess = "getresult" }, null))*@

@*@using (Html.BeginForm("Upload", "TPurchase", FormMethod.Post, new { enctype = "multipart/form-data" }))*@
@using (Ajax.BeginForm("Upload", "TPurchase", new AjaxOptions() { HttpMethod = "post", OnSuccess = "GetResult" }, new { id = "dialog", name = "dialog", enctype = "multipart/form-data" }))
{
    @*if (Model != null && Model.ID > 0)
        {
            @Html.HiddenFor(a => a.ID)
        }*@



    <div id="divDetails" class="row">
        <div>

        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label> &nbsp; </label><br />
                <label>Purchase Inv No:PUR-@(@DateTime.Now.Year % 100)-<span id="invno"></span></label>
                @*<label>Purchase Inv No:</label>
                    @Html.TextBoxFor(a => a.iPurchaseInvoiceNo, new { @class = "form-control", @id = "invno", disabled = "disabled" })
                    @Html.ValidationMessageFor(a => a.iPurchaseInvoiceNo)*@
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label>Purchase Inv Date:</label>
                @Html.TextBoxFor(a => a.strPurchaseInvoiceDate, new { @class = "form-control datepicker", @placeholder = "Enter Drop-off date here..." })
                @Html.ValidationMessageFor(a => a.strPurchaseInvoiceDate)
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <input type="hidden" id="hfSupplier" />
                <label>Supplier:</label>
                @Html.TextBoxFor(a => a.strSupplierName, new { @class = "form-control", @id = "txtSearchSupplier" })
                @Html.ValidationMessageFor(a => a.strSupplierName)
            </div>
        </div>

        @*<div class="col-sm-6">
                <div class="form-group">
                    &nbsp;
                </div>
            </div>*@

        <div class="col-sm-6">
            <div class="form-group">
                <label>Master Dec No:</label>
                @Html.TextBoxFor(a => a.strMasterDecNo, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.strMasterDecNo)
            </div>
        </div>


        <div class="col-sm-6">
            <div class="form-group">
                <label>Bill No:</label>
                @Html.TextBoxFor(a => a.strBLNo, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.strBLNo)
            </div>
        </div>


        <div class="col-sm-6">
            <div class="form-group">
                <label>Arrival Date:</label>
                @Html.TextBoxFor(a => a.strArrivalDate, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.strArrivalDate)
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <label>Invoice value:</label>
                @Html.TextBoxFor(a => a.strInvoiceValue, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.strInvoiceValue)
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label>Conversion Rate:</label>
                @Html.TextBoxFor(a => a.dmlConversionRate, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.dmlConversionRate)
            </div>

        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label>AED:</label>
                @Html.TextBoxFor(a => a.dcmlAED, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.dcmlAED)
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <label>Choose Excel File:</label>
                <input type="file" name="UploadedFile" />
            </div>
        </div>


        <div class="col-sm-6">
            <div class="form-group">
                <label>&nbsp;</label><br />
                <input type="submit" name="Submit" value="Import" />
            </div>
        </div>



    </div>



    @*<table>
            <tr>
                <td>File:</td>
                <td>
                    <input type="file" name="UploadedFile" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" name="Submit" value="Submit" />
                </td>
            </tr>
        </table>*@












}






<script type="text/javascript">
    $.ajax({
        url: '/TPurchase/GetInvoice/',
        dataType: "json",
        type: "POST",
        contentType: "application/json; charset=utf-8",
        success: function (data) {
            $("#invno").html(data);
        }
    });



</script>



<script type="text/javascript">
    $(function () { // will trigger when the document is ready
        $('.datepicker').datepicker({ dateFormat: 'mm/dd/yy' });//Initialise any date pickers
    });
</script>


<script type="text/javascript">
    $(function () {
        $("#txtSearchSupplier").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '/TPurchase/AutoComplete/',
                    data: "{ 'prefix': '" + request.term + "'}",
                    dataType: "json",
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        response($.map(data, function (item) {
                            return item;
                        }))
                    },
                    error: function (response) {
                        alert(response.responseText);
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    }
                });
            },
            select: function (e, i) {
                $("#hfSupplier").val(i.item.val);
            },
            minLength: 1
        });
    });
</script>

Views/TPurchase/SavePurchaseLot.cshtml
@model AuctionInventory.Models.Lots
@{
    ViewBag.Title = "SavePurchaseLot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("SavePurchaseLot", "TPurchase", FormMethod.Post, new { id = "popupForm" }))
{

    if (Model != null && Model.iLotID > 0)
    {
        @Html.HiddenFor(a => a.iLotID)

    }

    <div class="row">

        <div class="col-md-4">
            <div class="form-group">
                @Html.TextBoxFor(a => a.chLotType, new { @type = "hidden", @id = "hdnLotType" })
                <label>Lot Name:</label>
                @Html.TextBoxFor(a => a.strLotName, new { @class = "form-control", @id = "txtLotName" })
                @Html.ValidationMessageFor(a => a.strLotName)
            </div>
        </div>
        <div class="col-md-4">

            <div class="form-group">
                <label>From Date:</label>
                @Html.TextBoxFor(a => a.dtFromDate, new { @type = "hidden", @id = "dtFromDate" })

                @Html.TextBoxFor(a => a.strFromDate, new { @class = "form-control datepicker", @name = "DateTextBox", @id = "txtFromDate", @placeholder = "Enter Drop-off date here..." })
                @Html.ValidationMessageFor(a => a.strFromDate)
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label>To Date:</label>

                @Html.TextBoxFor(a => a.dtToDate, new { @type = "hidden", @id = "dtToDate" })

                @Html.TextBoxFor(a => a.strToDate, new { @class = "form-control datepicker", @name = "DateTextBox", @id = "txtToDate", @placeholder = "Enter Drop-off date here..." })
                @Html.ValidationMessageFor(a => a.strToDate)
            </div>

        </div>

        <input type="submit" name='dailogBox' style="margin-left: 400px;" id="btnSave" class="btn btn-success col-md-1" value="Save">
    </div>

}
<br />
@*<div>
        <table id="dataGrid" class="table table-bordered table-striped"></table>
        <div id="pagingGrid"></div>
        <br><br>
    </div>*@

<script type="text/javascript">
    $(function () { // will trigger when the document is ready

        debugger
        $('.datepicker').datepicker({ dateFormat: 'mm/dd/yy' }); //Initialise any date pickers
        //$("#txtFromDate").datepicker().datepicker("setDate", new Date());

        $('.datepicker').datepicker({ dateFormat: 'mm/dd/yy' }); //Initialise any date pickers
        //$("#txtToDate").datepicker().datepicker("setDate", new Date());


        //$("#dtFromDate").val($("#txtFromDate").val());
        //$("#dtToDate").val($("#txtToDate").val());
        $("#hdnLotType").val('P');

        if (Model.iLotID == 0) {

            $("#txtFromDate").val("");
            $("#txtToDate").val("");
            $("#hdnLotType").val("");
            $("#dtFromDate").val("");
            $("#dtToDate").val("");
            $("#txtLotName").val("");

        }

    });

    $("#btnSave").click(function () {
        $("#dtFromDate").val($("#txtFromDate").val());
        $("#dtToDate").val($("#txtToDate").val());
    });

</script>



<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/redmond/jquery-ui.css" />

Views/TPurchase/Upload.cshtml
@*@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta name="viewport" content="width=device-width" />
<title>Index</title>

@using (Html.BeginForm("Upload", "TPurchase", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <table>
        <tr>
            <td>File:</td>
            <td>
                <input type="file" name="UploadedFile" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="Submit" value="Submit" />
            </td>
        </tr>
    </table>
}*@  

<input type="file" id="FileUpload1" />
<input type="button" id="btnUpload" value="Upload Files" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>

    $(document).ready(function(){
        $('#btnUpload').click(function () {

            // Checking whether FormData is available in browser
            if (window.FormData !== undefined) {

                var fileUpload = $("#FileUpload1").get(0);
                var files = fileUpload.files;

                // Create FormData object
                var fileData = new FormData();

                // Looping over all files and add it to FormData object
                for (var i = 0; i < files.length; i++) {
                    fileData.append(files[i].name, files[i]);
                }

                // Adding one more key to FormData object
                fileData.append('username', 'Salman');

                $.ajax({
                    url: '/TPurchase/UploadFiles',
                    type: "POST",
                    contentType: false, // Not to set any content header
                    processData: false, // Not to process data
                    data: fileData,
                    success: function (result) {
                        alert(result);
                    },
                    error: function (err) {
                        alert(err.statusText);
                    }
                });
            } else {
                alert("FormData is not supported.");
            }
        });
    });
</script> 