Controllers/MCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionInventoryDAL.Entity;
using AuctionInventoryDAL.Repositories;
using AuctionInventory.Services;
using AuctionInventory.Models;
using AuctionInventory.Helpers;
using AuctionInventory.MyRoleProvider;
using System.Security.Cryptography;
using System.IO;
using System.Text;
namespace AuctionInventory.Controllers
{
    [Permissions(Permissions.View)]
    public class MCategoryController : Controller
    {
        // GET: MCategory
        public ActionResult Index()
        {
            ViewBag.PageName = "Category List";
            return View();
        }

        #region CRUD
        public ActionResult GetAllCategory()
        {
            dynamic category = 0;

            try
            {
                if (ModelState.IsValid)
                {
                    CategoryServiceClient categoryServiceClient = new CategoryServiceClient();
                    category = categoryServiceClient.GetAllCategory();
                    //if (category.Count == 0 || category == null)
                    //{
                    //    ModelState.AddModelError("error", "No Record Found");
                    //}


                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Wrong");
                category = null;
                throw e;
            }
            return Json(category, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult Save(String ID)
        {
            int id = 0;
            if (ID != "0")
            {
                id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));
            }
            Category category = new Category();
            try
            {
                if (ModelState.IsValid)
                {

                    Services.CategoryServiceClient categoryServiceClient = new Services.CategoryServiceClient();
                    category = categoryServiceClient.GetCategory(id);
                    //ViewBag.Status = "Update";
                    ViewBag.PageName = "Create Category";
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                category = null;
                throw e;
            }
            return View("Save", category);
            //return View(category);
        }

        [HttpPost]
        public ActionResult Save(Category category)
        {
            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CategoryServiceClient categoryServiceClient = new Services.CategoryServiceClient();
                    status = categoryServiceClient.SaveData(category);
                    return RedirectToAction("Index");
                }

            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong");
                status = false;
                throw e;

            }
            return View(category);

            //return View();
            // return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        public ActionResult Delete(String ID)
        {
            int id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));
            Category category = new Category();
            try
            {
                if (ModelState.IsValid)
                {

                    Services.CategoryServiceClient categoryServiceClient = new Services.CategoryServiceClient();
                    category = categoryServiceClient.GetCategory(id);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                category = null;
                throw e;
            }
            return View(category);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteCategory(String ID)
        {
            int id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));
            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CategoryServiceClient categoryServiceClient = new Services.CategoryServiceClient();
                    status = categoryServiceClient.Delete(id);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong!");
                status = false;
                throw e;
            }

            return View("Index");
            //return new JsonResult { Data = new { status = status } };

        }



        #endregion
    }
}

Views/MCategory/Delete.cshtml
@model AuctionInventory.Models.Category
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("delete", "MCategory", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.iCategoryID)
    @*<div class="form-group">
        <label>Category Name</label>
        <p>@Model.strCategoryName</p>
    </div>*@
    
     <div class="form-group col-xs-5">
        <label>Category Name</label>
        @Html.TextBoxFor(a => a.strCategoryName, new { @class = "form-control  input-group-lg", @placeholder = "Enter Category Name" })
       
    </div>
    
    <div>
        @*<input type="submit" value="Delete" />*@
        <input type="submit" style="margin-left: -350px; margin-top: 100px; " class="btn btn-danger col-md-1" value="Delete">
        
        <input type="button" style="margin-left: -210px;margin-top: 100px;" class="btn btn-warning col-md-1" value="Cancel" onclick="CancelCategoryInfo();" />

    </div>
    
   
}

<script>
    function CancelCategoryInfo() {
        window.location.href = "/MCategory/Index";
    }
</script>
   

Views/MCategory/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta name="viewport" content="width=device-width" />
<title>Index</title>
<style>
    span.field-validation-error {
        color: red;
    }
    /*we have overrides the css to change border color of menus*/
    .navbar-inverse {
        background-color: #337ab7;
        border-color: #333;
    }
</style>

<div class="box-body">
    <div>
        <a class="popup btn btn-primary" href="/MCategory/Save/0" style="margin-bottom:20px; margin-top:20px;">Add New Category</a>

    </div>
    <br />
    <div>
        <table id="dataGrid" class="table table-bordered table-striped"></table>
        <div id="pagingGrid"></div>
        <br><br>
    </div>
</div>



<script>
    $(function () {

        //this grid is used to fill the Category list

        $('#dataGrid').jqGrid({
            caption: "Category List",
            url: '/MCategory/GetAllCategory/',
            datatype: "json",
            contentType: "application/json; charset-utf-8",
            mtype: 'GET',

            colNames: ['iCategoryID', 'Category Name', 'Action'],
            colModel: [
                { name: 'iCategoryID', index: 'iCategoryID', hidden: true, hidedlg: true },
                { name: 'strCategoryName', index: 'strCategoryName',align:'center' },
             
                   {
                       name: 'Action', index: 'Action', align: 'center', width: 100, search: false, title: false,
                       formatter: function (cellvalue, options, rowObject) {

                           return '<a class="popup btn btn-warning"  href="/MCategory/Save/' + options.rowId + '">Edit</a>' + "   " + '<a class="popup btn btn-danger"  href="/MCategory/Delete/' + options.rowId + '">Delete</a>';

                           //return  "<input class='popup btn btn-info' style='margin-right: 5%; ' type='button' value='Edit'  onclick=\"editRowData('" + options.rowId + "');\"  />";
                       }

                   },

                

            ],
            width: 800,
            height: 250,
            rowNum: 10,
            loadonce: true,
            ignoreCase: true,
            rowList: [10, 20, 30],
            pager: 'pagingGrid',
        });
        jQuery("#dataGrid").jqGrid('filterToolbar', { stringResult: true, searchOnEnter: false, defaultSearch: "cn" });
        jQuery("#dataGrid").jqGrid('navGrid', '#pagingGrid', { edit: false, add: false, del: false, search: false });

    });
</script>


<!-- JqGrid Scripts -->
<link href="~/scripts/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
<link href="~/scripts/ui.jqgrid.css" rel="stylesheet" />
<script src="~/Scripts/jQuery-migrate-1.2.1-min.js"></script>
<script src="~/scripts/jQuery-migrate-1.2.1.js"></script>
<script src="~/scripts/grid.locale-en.js"></script>
<script src="~/scripts/jquery.jqgrid.min.js"></script>

<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/redmond/jquery-ui.css" />

Views/MCategory/Save.cshtml
@model AuctionInventory.Models.Category
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .error {
        color: red;
    }
</style>

@using (Html.BeginForm("Save", "MCategory", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.ValidationSummary(true)
    if (Model != null && Model.iCategoryID > 0)
    {
        @Html.HiddenFor(a => a.iCategoryID)
    }
    <div class="form-group col-xs-5">
        <label>Category Name</label>
        @Html.TextBoxFor(a => a.strCategoryName, new { @class = "form-control  input-group-lg", @placeholder = "Enter Category Name" })
        @Html.ValidationMessageFor(m => m.strCategoryName, "", new { @class = "error" })

    </div>

    <div>
        @if (Model != null && Model.iCategoryID > 0 && Model.iCategoryID != null)
        {
            <input type="submit" style="margin-left: -350px; margin-top: 100px;" class="btn btn-warning col-md-1" value="Update">
        }
        else
        {
            <input type="submit" style="margin-left: -350px; margin-top: 100px;" class="btn btn-success col-md-1" value="Save">
        }

        @*<input type="submit" value="Save" />*@

        <input type="button" style="margin-left: -210px;margin-top: 100px;" class="btn btn-warning col-md-1" value="Cancel" onclick="CancelCategoryInfo();" />

    </div>
}
<script>
    function CancelCategoryInfo() {
        window.location.href = "/MCategory/Index";
    }

</script>