Controllers/MCreditCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionInventoryDAL.Entity;
using AuctionInventoryDAL.Repositories;
using AuctionInventory.Services;
using AuctionInventory.Models;
using AuctionInventory.Helpers;
using AuctionInventory.MyRoleProvider;

namespace AuctionInventory.Controllers
{
      [Permissions(Permissions.View)]
    public class MCreditCategoryController : Controller
    {
        //
        // GET: /MCreditCategory/
        public ActionResult Index()
        {
            return View();
        }


        #region CRUD
        public ActionResult GetAllCreditCategory()
        {
            dynamic category = 0;

            try
            {
                if (ModelState.IsValid)
                {
                    CreditCategoryServiceClient service = new CreditCategoryServiceClient();
                    category = service.GetAllCategory();
                    //if (category.Count == 0 || category == null)
                    //{
                    //    ModelState.AddModelError("error", "No Record Found");
                    //}


                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Wrong");
                category = null;
                throw e;
            }
            return Json(category, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult Save(int id)
        {
            CreditCategoryModel category = new CreditCategoryModel();
            try
            {
                if (ModelState.IsValid)
                {

                    Services.CreditCategoryServiceClient categoryServiceClient = new Services.CreditCategoryServiceClient();
                    category = categoryServiceClient.GetCategory(id);
                    //ViewBag.Status = "Update";
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                category = null;
                throw e;
            }
            return View("Save", category);
            //return View(category);
        }

        [HttpPost]
        public ActionResult Save(CreditCategoryModel category)
        {
            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CreditCategoryServiceClient categoryServiceClient = new Services.CreditCategoryServiceClient();
                    status = categoryServiceClient.SaveData(category);
                    return RedirectToAction("Index");
                }

            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong");
                status = false;
                throw e;

            }
            return View(category);

            //return View();
            // return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            CreditCategoryModel category = new CreditCategoryModel();
            try
            {
                if (ModelState.IsValid)
                {

                    Services.CreditCategoryServiceClient categoryServiceClient = new Services.CreditCategoryServiceClient();
                    category = categoryServiceClient.GetCategory(id);
                    //ViewBag.Status = "Update";
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                category = null;
                throw e;
            }
            return View(category);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteCategory(int id)
        {
            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CreditCategoryServiceClient categoryServiceClient = new Services.CreditCategoryServiceClient();
                    status = categoryServiceClient.Delete(id);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong!");
                status = false;
                throw e;
            }

            return View("Index");
            //return new JsonResult { Data = new { status = status } };

        }

        #endregion
	}
}

Views/MCreditCategory/Delete.cshtml
@model AuctionInventory.Models.CreditCategoryModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .error {
        color: red;
    }
</style>

@using (Html.BeginForm("delete", "MCreditCategory", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.ValidationSummary(true)
    if (Model != null && Model.iCreditCategoryID > 0)
    {
        @Html.HiddenFor(a => a.iCreditCategoryID)
    }
    <div class="form-group col-xs-5">
        <label>Category Name</label>
        @Html.TextBoxFor(a => a.strCategory, new { @class = "form-control  input-group-lg", @placeholder = "Enter Category Name" })
        @Html.ValidationMessageFor(m => m.strCategory, "", new { @class = "error" })

    </div>
    <div class="form-group col-xs-5">
        <label>Days</label>
        @Html.TextBoxFor(a => a.iDays, new { @class = "form-control  input-group-lg", @placeholder = "Enter Days", @type = "number" })
        @Html.ValidationMessageFor(m => m.iDays, "", new { @class = "error" })

    </div>
   <div>
        @*<input type="submit" value="Delete" />*@
        <input type="submit" style="margin-left: -350px; margin-top: 100px; " class="btn btn-danger col-md-1" value="Delete">
        
        <input type="button" style="margin-left: -210px;margin-top: 100px;" class="btn btn-warning col-md-1" value="Cancel" onclick="CancelCategoryInfo();" />

    </div>
    
}
<script>
    function CancelCategoryInfo() {
        window.location.href = "/MCreditCategory/Index";
    }

</script>

Views/MCreditCategory/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta name="viewport" content="width=device-width" />
<title>Index</title>
<style>
    span.field-validation-error {
        color: red;
    }
    /*we have overrides the css to change border color of menus*/
    .navbar-inverse {
        background-color: #337ab7;
        border-color: #333;
    }
</style>

<div class="box-body">
    <div>
        <a class="popup btn btn-primary" href="/MCreditCategory/Save/0" style="margin-bottom:20px; margin-top:20px;">Add New</a>

    </div>
    <br />
    <div>
        <table id="dataGrid" class="table table-bordered table-striped"></table>
        <div id="pagingGrid"></div>
        <br><br>
    </div>
</div>



<script>
    $(function () {

        //this grid is used to fill the Category list

        $('#dataGrid').jqGrid({
            caption: "Category List",
            url: '/MCreditCategory/GetAllCreditCategory/',
            datatype: "json",
            contentType: "application/json; charset-utf-8",
            mtype: 'GET',

            colNames: ['iCreditCategoryID', 'Category Name', 'Days', 'Action'],
            colModel: [
                

                { name: 'iCreditCategoryID', index: 'iCreditCategoryID', hidden: true, hidedlg: true },
                { name: 'strCategory', index: 'strCategory', align: 'center' },
                 { name: 'iDays', index: 'iDays', align: 'center' },

                   {
                       name: 'Action', index: 'Action', align: 'center', width: 100, search: false, title: false,
                       formatter: function (cellvalue, options, rowObject) {

                           return '<a class="popup btn btn-warning"  href="/MCreditCategory/Save/' + options.rowId + '">Edit</a>' + "   " + '<a class="popup btn btn-danger"  href="/MCreditCategory/Delete/' + options.rowId + '">Delete</a>';

                           //return  "<input class='popup btn btn-info' style='margin-right: 5%; ' type='button' value='Edit'  onclick=\"editRowData('" + options.rowId + "');\"  />";
                       }

                   },



            ],
            width: 800,
            height: 250,
            rowNum: 10,
            loadonce: true,
            ignoreCase: true,
            rowList: [10, 20, 30],
            pager: 'pagingGrid',
        });
        jQuery("#dataGrid").jqGrid('filterToolbar', { stringResult: true, searchOnEnter: false, defaultSearch: "cn" });
        jQuery("#dataGrid").jqGrid('navGrid', '#pagingGrid', { edit: false, add: false, del: false, search: false });

    });
</script>


<!-- JqGrid Scripts -->
<link href="~/scripts/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
<link href="~/scripts/ui.jqgrid.css" rel="stylesheet" />
<script src="~/Scripts/jQuery-migrate-1.2.1-min.js"></script>
<script src="~/scripts/jQuery-migrate-1.2.1.js"></script>
<script src="~/scripts/grid.locale-en.js"></script>
<script src="~/scripts/jquery.jqgrid.min.js"></script>

Views/MCreditCategory/Save.cshtml
@model AuctionInventory.Models.CreditCategoryModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .error {
        color: red;
    }
</style>

@using (Html.BeginForm("Save", "MCreditCategory", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.ValidationSummary(true)
    if (Model != null && Model.iCreditCategoryID > 0)
    {
        @Html.HiddenFor(a => a.iCreditCategoryID)
    }
    <div class="form-group col-xs-5">
        <label>Category Name</label>
        @Html.TextBoxFor(a => a.strCategory, new { @class = "form-control  input-group-lg", @placeholder = "Enter Category Name" })
        @Html.ValidationMessageFor(m => m.strCategory, "", new { @class = "error" })

    </div>
     <div class="form-group col-xs-5">
        <label>Days</label>
        @Html.TextBoxFor(a => a.iDays, new { @class = "form-control  input-group-lg", @placeholder = "Enter Days",@type="number" })
        @Html.ValidationMessageFor(m => m.iDays, "", new { @class = "error" })

    </div>
    <div>
        @if (Model != null && Model.iCreditCategoryID > 0 && Model.iCreditCategoryID != null)
        {
            <input type="submit" style="margin-left: -350px; margin-top: 100px;" class="btn btn-warning col-md-1" value="Update">
        }
        else
        {
            <input type="submit" style="margin-left: -350px; margin-top: 100px;" class="btn btn-success col-md-1" value="Save">
        }

        @*<input type="submit" value="Save" />*@

        <input type="button" style="margin-left: -210px;margin-top: 100px;" class="btn btn-warning col-md-1" value="Cancel" onclick="CancelCategoryInfo();" />

    </div>
}
<script>
    function CancelCategoryInfo() {
        window.location.href = "/MCreditCategory/Index";
    }

</script>