Controllers/MCurrencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionInventoryDAL.Entity;
using AuctionInventoryDAL.Repositories;
using AuctionInventory.Services;
using AuctionInventory.Models;
using AuctionInventory.Helpers;
using AuctionInventory.MyRoleProvider;
using System.Security.Cryptography;
using System.IO;
using System.Text;
namespace AuctionInventory.Controllers
{
    [Permissions(Permissions.View)]
    public class MCurrencyController : Controller
    {
        // GET: MCurrency
        public ActionResult Index()
        {
            ViewBag.PageName = "Currency List";
            return View();
        }

        #region CRUD
        public ActionResult GetAllCurrency()
        {
            dynamic currency = 0;
           
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CurrencyServiceClient currencyServiceClient = new Services.CurrencyServiceClient();
                    currency = currencyServiceClient.GetAllCurrency();
                    //if (currency.Count == 0 || currency == null)
                    //{
                    //    ModelState.AddModelError("error", "No Record Found");
                    //}
                    
                }
            }
             catch(Exception e)
            {
                ModelState.AddModelError("error", "Something Wrong");
                currency = null;
                throw e;

            }
            return Json(currency, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult Save(String ID)
        {
            int id = 0;
            if (ID != "0")//ID=0 for new record
            {
                id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));
            }
           Currency currency = new Currency();
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CurrencyServiceClient currencyServiceClient = new Services.CurrencyServiceClient();
                    
                    currency = currencyServiceClient.GetCurrency(id);
                    //ViewBag.Status = "Save";
                    //ViewBag.Status = "Update";
                    ViewBag.PageName = "Create Currency";
                }
            }
             catch(Exception e)
            {
                ModelState.AddModelError("error", "something went wrong");
                currency = null;
                throw e;
            }
            return View(currency);
        }

        [HttpPost]
        public ActionResult Save(Currency currency)
        {
            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CurrencyServiceClient currencyServiceClient = new Services.CurrencyServiceClient();
                    
                    status = currencyServiceClient.SaveData(currency);
                    return RedirectToAction("Index");
                }
            }
             catch(Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong");
                status = false;
                throw e;
            }

            return View();
           // return new JsonResult { Data = new { status = status } };
        }


        [HttpGet]
        public ActionResult Delete(String ID)
        {

            int id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));//Decrypt ID
            
            Currency currency = new Currency();
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CurrencyServiceClient currencyServiceClient = new Services.CurrencyServiceClient();
                    
                    currency = currencyServiceClient.GetCurrency(id);
                }
            }
             catch(Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong");
                currency = null;
                throw e;
            }
            return View(currency);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteCurrency(String ID)
        {

            int id = Convert.ToInt32(Helpers.CommonMethods.Decrypt(HttpUtility.UrlDecode(ID)));//Decrypt ID
            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    Services.CurrencyServiceClient currencyServiceClient = new Services.CurrencyServiceClient();
                   
                    status = currencyServiceClient.Delete(id);
                }
            }
             catch(Exception e)
            {
                ModelState.AddModelError("error", "Something Went Wrong!");
                status = false;
                throw e;
            }
            return View("Index");
            //return new JsonResult { Data = new { status = status } };

        }

        

        #endregion
    }
}

Views/MCurrency/Delete.cshtml
@*@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@
@model AuctionInventory.Models.Currency
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("delete", "MCurrency", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.CurrencyID)
    <div class="form-group col-xs-5">
        <div class="form-group">
            <label>Currency Name</label>
            @Html.TextBoxFor(a => a.strCurrencyName, new { @class = "form-control input-group-lg", @placeholder = "Enter Currency Name" })
            @Html.ValidationMessageFor(m => m.strCurrencyName, "", new { @class = "error" })

        </div>
        <div class="form-group">
            <label>Currency ShortName</label>
            @Html.TextBoxFor(a => a.strCurrencyShortName, new { @class = "form-control input-group-lg", @placeholder = "Enter Currency Short Name" })
            @Html.ValidationMessageFor(m => m.strCurrencyShortName, "", new { @class = "error" })

        </div>
    </div>
    
      <div>
          
        @*<input type="submit" value="Delete" />*@
        <input type="submit" style="margin-left: -350px; margin-top: 180px; " class="btn btn-danger col-md-1" value="Delete">
        
        <input type="button" style="margin-left: -210px; margin-top: 180px; " class="btn btn-warning col-md-1" value="Cancel" onclick="CancelCurrencyInfo();" />

    </div>
}

<script>
    function CancelCurrencyInfo() {
        window.location.href = "/MCurrency/Index";
    }

</script>

Views/MCurrency/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta name="viewport" content="width=device-width" />
<title>Index</title>
<style>
    span.field-validation-error {
        color: red;
    }
    /*we have overrides the css to change border color of menus*/
    .navbar-inverse {
        background-color: #337ab7;
        border-color: #333;
    }
</style>
@*<div style="width:90%; margin:70px auto" class="tablecontainer">
    <a class="popup btn btn-primary" href="/MCurrency/save/0" style="margin-bottom:20px; margin-top:20px;">Add New Currency</a>
    <table id="myDatatable">
        <thead>
            <tr>
                <th>Currency Name</th>
                <th>Currency ShortName</th>                
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
    </table>
</div>
<script>
    $(document).ready(function () {
        var oTable = $('#myDatatable').DataTable({
            //"scrollY": 200,
            //"scrollX": true,
            "ajax": {
                "url": '/MCurrency/GetAllCurrency',
                "type": "get",
                "datatype": "json"
            },
            "columns": [
                { "data": "strCurrencyName", "autoWidth": true },
                { "data": "strCurrencyShortName", "autoWidth": true },
               
                {
                    "data": "CurrencyID", "width": "50px", "render": function (data) {
                        return '<a class="popup" href="/MCurrency/save/' + data + '">Edit</a>';
                    }
                },
                {
                    "data": "CurrencyID", "width": "50px", "render": function (data) {
                        return '<a class="popup" href="/MCurrency/delete/' + data + '">Delete</a>';
                    }
                }
            ]
        })
        //$('.tablecontainer').on('click', 'a.popup', function (e) {
        //    e.preventDefault();
        //    OpenPopup($(this).attr('href'));
        //})
        function OpenPopup(pageUrl) {
            var $pageContent = $('<div/>');
            $pageContent.load(pageUrl, function () {
                $('#popupForm', $pageContent).removeData('validator');
                $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                $.validator.unobtrusive.parse('form');

            });

            $dialog = $('<div class="popupWindow" style="overflow:auto"></div>')
                      .html($pageContent)
                      .dialog({
                          draggable: false,
                          autoOpen: false,
                          resizable: false,
                          model: true,
                          title: 'Popup Dialog',
                          height: 550,
                          width: 600,
                          close: function () {
                              $dialog.dialog('destroy').remove();
                          }
                      })

            $('.popupWindow').on('submit', '#popupForm', function (e) {
                var url = $('#popupForm')[0].action;
                $.ajax({
                    type: "POST",
                    url: url,
                    data: $('#popupForm').serialize(),
                    success: function (data) {
                        if (data.status) {
                            $dialog.dialog('close');
                            oTable.ajax.reload();
                        }
                    }
                })

                e.preventDefault();
            })

            $dialog.dialog('open');
        }
    })
</script>*@


<div class="box-body">
    <div>
        <a class="popup btn btn-primary" href="/MCurrency/save/0" style="margin-bottom:20px; margin-top:20px;">Add New Currency</a>

    </div>
    <br />
    <div>
        <table id="dataGrid" class="table table-bordered table-striped"></table>
        <div id="pagingGrid"></div>
        <br><br>
    </div>
</div>



<script>
    $(function () {

        //this grid is used to fill the Category list

        $('#dataGrid').jqGrid({
            caption: "Currency List",
            url: '/MCurrency/GetAllCurrency/',
            datatype: "json",
            contentType: "application/json; charset-utf-8",
            mtype: 'GET',

            colNames: ['CurrencyID', 'Currency Name', 'Currency Short Name', 'Action'],
            colModel: [
                { name: 'CurrencyID', index: 'CurrencyID', hidden: true, hidedlg: true },
                { name: 'strCurrencyName', index: 'strCurrencyName', align: 'center' },
                 { name: 'strCurrencyShortName', index: 'strCurrencyShortName', align: 'center' },

                   {
                       name: 'Action', index: 'Action', align: 'center', width: 100, search: false, title: false,
                       formatter: function (cellvalue, options, rowObject) {

                           return '<a class="popup btn btn-warning" href="/MCurrency/save/' + options.rowId + '">Edit</a>' + "   " + '<a class="popup btn btn-danger"  href="/MCurrency/delete/' + options.rowId + '">Delete</a>';

                           //return  "<input class='popup btn btn-info' style='margin-right: 5%; ' type='button' value='Edit'  onclick=\"editRowData('" + options.rowId + "');\"  />";
                       }

                   },



            ],
            width: 800,
            height: 250,
            rowNum: 10,
            loadonce: true,
            ignoreCase: true,
            rowList: [10, 20, 30],
            pager: 'pagingGrid',
        });
        jQuery("#dataGrid").jqGrid('filterToolbar', { stringResult: true, searchOnEnter: false, defaultSearch: "cn" });
        jQuery("#dataGrid").jqGrid('navGrid', '#pagingGrid', { edit: false, add: false, del: false, search: false });

    });
</script>


<!-- JqGrid Scripts -->
<link href="~/scripts/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
<link href="~/scripts/ui.jqgrid.css" rel="stylesheet" />
<script src="~/Scripts/jQuery-migrate-1.2.1-min.js"></script>
<script src="~/scripts/jQuery-migrate-1.2.1.js"></script>
<script src="~/scripts/grid.locale-en.js"></script>
<script src="~/scripts/jquery.jqgrid.min.js"></script>

<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/redmond/jquery-ui.css" />

Views/MCurrency/Save.cshtml
@model AuctionInventory.Models.Currency
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .error {
        color: red;
    }
</style>


@using (Html.BeginForm("Save", "MCurrency", FormMethod.Post, new { id = "popupForm" }))
{
     @Html.ValidationSummary(true)
    if (Model != null && Model.CurrencyID > 0)
    {
        @Html.HiddenFor(a => a.CurrencyID)
    }
    <div class="form-group col-xs-5">
        <div class="form-group">
            <label>Currency Name</label>
            @Html.TextBoxFor(a => a.strCurrencyName, new { @class = "form-control input-group-lg", @placeholder = "Enter Currency Name" })
            @Html.ValidationMessageFor(m => m.strCurrencyName, "", new { @class = "error" })

        </div>
        <div class="form-group">
            <label>Currency ShortName</label>
            @Html.TextBoxFor(a => a.strCurrencyShortName, new { @class = "form-control input-group-lg", @placeholder = "Enter Currency Short Name" })
            @Html.ValidationMessageFor(m => m.strCurrencyShortName, "", new { @class = "error" })

        </div>
    </div>
  
    
       <div>
        @if (Model.CurrencyID > 0)
        {
            <input type="submit" style="margin-left: -350px; margin-top: 180px;" class="btn btn-warning col-md-1" value="Update">
        }
        else
        {
            <input type="submit" style="margin-left: -350px; margin-top: 180px;" class="btn btn-success col-md-1" value="Save">
        }

        @*<input type="submit" value="Save" />*@

        <input type="button" style="margin-left: -210px; margin-top: 180px;" class="btn btn-warning col-md-1" value="Cancel" onclick="CancelCurrencyInfo();" />

    </div>
}

<script>
    function CancelCurrencyInfo() {
        window.location.href = "/MCurrency/Index";
    }

</script>